
server:
  port: 9070

spring:
  application:
    name: SUBSCRIBE-SERVICE
  data:
    mongodb:
      host: localhost
      port: 27017
      database: my-blog
      
  mail:
    host: smtp.gmail.com
    port: 587
    username: jrrchowdary9821@gmail.com
    password: zphkfkmzcizfrlrb
    
    properties:
      mail:
        smtp:
          auth: true
          starttls:
              enable: true
      
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
              
#logging:
#  level:
#    root: info
#  pattern:
#    file:  "%d{yyyy-MM-dd HH:mm:ss} [%thread] %logger{36} %-5level - %msg%n" 
#  file:
#    name: ./SUBSCRBE.log
#    max-size: 15KB
#    max-history: 5
#    
#    clean-history-on-start: true
  

      


